
name: Test

on:
  push:
  pull_request:

env:
  CGO_ENABLED: 0

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'
        
    - name: Test
      run: make test
